// constants/constants.ts

/**
 * A centralized object for storing Tailwind CSS class string constants
 * used across various UI elements, supporting dark and light themes.
 * This promotes consistency and ease of maintenance.
 */
export const classConstants = {
  dark: {
    button: {
      base: 'inline-flex items-center px-4 py-2.5 text-sm font-semibold rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-900 focus:ring-sky-500 transition-all duration-150 ease-in-out disabled:opacity-60 disabled:cursor-not-allowed',
      defaultLayout: 'justify-center',
      primary: 'border border-transparent text-white bg-sky-600 hover:bg-sky-500',
      danger: 'border border-transparent text-white bg-rose-500 hover:bg-rose-600',
      item: 'justify-between bg-slate-700 hover:bg-slate-600 text-white font-semibold',
      link: 'bg-transparent hover:bg-slate-700 text-slate-300 hover:text-white shadow-none px-2 py-2 font-normal justify-start',
      secondary: 'border border-slate-600 hover:bg-slate-700 text-slate-300',
      iconBase: 'w-5 h-5',
      iconMarginLeft: 'mr-2',
      iconMarginRight: 'ml-2',
    },
    formField: {
      base: 'w-full px-3 py-2.5 bg-slate-700 border border-slate-600 rounded-md text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition-shadow disabled:opacity-70 disabled:cursor-not-allowed',
      error: 'border-red-500 focus:ring-red-500 focus:border-red-500',
    },
    fieldBase: {
      label: 'block text-sm font-medium text-slate-300 mb-1',
      requiredAsterisk: 'text-red-400 ml-1',
      errorText: 'mt-1.5 text-xs text-red-400',
      errorPlaceholder: 'mt-1.5 text-xs text-transparent select-none',
    },
    toggleSwitch: {
      base: 'relative inline-flex items-center h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none',
      focus: 'ring-2 ring-sky-500 ring-offset-2 ring-offset-slate-800',
      checked: 'bg-sky-600',
      unchecked: 'bg-slate-600',
      disabled: 'opacity-50 cursor-not-allowed',
      enabledUncheckedHover: 'hover:bg-slate-500',
      error: 'border-red-500',
      thumbBase: 'pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out',
      thumbChecked: 'translate-x-5',
      thumbUnchecked: 'translate-x-0',
      labelBase: 'text-sm font-medium text-slate-300 select-none',
      labelDisabled: 'cursor-not-allowed opacity-70',
      labelEnabled: 'cursor-pointer',
      labelSpacingLeft: 'mr-3',
      labelSpacingRight: 'ml-3',
      errorPaddingLeftLabel: 'pl-10 sm:pl-12',
    },
    checkbox: {
      visualBase: 'h-5 w-5 flex-shrink-0 inline-flex items-center justify-center border rounded mr-2 transition-all duration-150 ease-in-out',
      focus: 'ring-2 ring-sky-500 ring-offset-2 ring-offset-slate-800',
      checked: 'bg-sky-600 border-sky-600',
      unchecked: 'bg-slate-700 border-slate-600',
      hoverChecked: 'hover:bg-sky-500 hover:border-sky-500',
      hoverUnchecked: 'hover:border-slate-500',
      disabled: 'opacity-60 cursor-not-allowed',
      errorUnchecked: 'border-red-500',
      labelBase: 'text-sm font-medium text-slate-300 select-none',
      labelDisabled: 'cursor-not-allowed opacity-70',
      labelEnabled: 'cursor-pointer',
      checkIcon: 'w-4 h-4 text-white',
      errorPaddingLeft: 'pl-7',
    },
    select: {
      buttonBase: 'w-full flex items-center justify-between px-3 py-2.5 bg-slate-700 border border-slate-600 rounded-md text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition-shadow disabled:opacity-70 disabled:cursor-not-allowed text-left',
      buttonError: 'border-red-500 focus:ring-red-500 focus:border-red-500',
      dropdownUl: 'absolute z-10 w-full mt-1 bg-slate-700 border border-slate-600 rounded-md shadow-lg max-h-60 overflow-y-auto focus:outline-none',
      optionBase: 'px-3 py-2 text-sm flex items-center justify-between cursor-pointer',
      optionDisabled: 'text-slate-500 cursor-not-allowed',
      optionEnabled: 'text-slate-200 hover:bg-slate-600',
      optionFocusedEnabled: 'bg-slate-600',
      noOptionsLi: 'px-3 py-2 text-slate-400 text-sm',
      expandIcon: 'w-5 h-5 text-slate-400 transform transition-transform duration-200',
      expandIconOpenState: 'rotate-180',
      placeholderText: 'text-slate-400',
      optionLeadingIcon: 'w-5 h-5 mr-2 text-slate-400 flex-shrink-0',
      optionSelectedCheckIcon: 'w-5 h-5 text-sky-400 flex-shrink-0',
    },
    sidebarLayout: {
      container: 'flex',
      sidebar: 'flex-shrink-0 bg-slate-800 text-white',
      main: 'flex-grow bg-slate-900 text-white overflow-y-auto',
    }
  },
  light: {
    button: {
      base: 'inline-flex items-center px-4 py-2.5 text-sm font-semibold rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-sky-500 transition-all duration-150 ease-in-out disabled:opacity-60 disabled:cursor-not-allowed',
      defaultLayout: 'justify-center',
      primary: 'border border-transparent text-white bg-sky-600 hover:bg-sky-700',
      danger: 'border border-transparent text-white bg-rose-500 hover:bg-rose-600',
      item: 'justify-between bg-gray-100 hover:bg-gray-200 text-slate-800 font-semibold',
      link: 'bg-transparent hover:bg-gray-100 text-sky-700 hover:text-sky-800 shadow-none px-2 py-2 font-normal justify-start',
      secondary: 'bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 hover:text-slate-800',
      iconBase: 'w-5 h-5',
      iconMarginLeft: 'mr-2',
      iconMarginRight: 'ml-2',
    },
    formField: {
      base: 'w-full px-3 py-2.5 bg-white border-gray-300 rounded-md text-slate-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition-shadow disabled:bg-gray-100 disabled:text-gray-500 disabled:cursor-not-allowed',
      error: 'border-red-500 text-red-700 placeholder-red-400 focus:ring-red-500 focus:border-red-500',
    },
    fieldBase: {
      label: 'block text-sm font-medium text-slate-700 mb-1',
      requiredAsterisk: 'text-red-500 ml-1',
      errorText: 'mt-1.5 text-xs text-red-600',
      errorPlaceholder: 'mt-1.5 text-xs text-transparent select-none',
    },
    toggleSwitch: {
      base: 'relative inline-flex items-center h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none',
      focus: 'ring-2 ring-sky-500 ring-offset-2 ring-offset-white',
      checked: 'bg-sky-600',
      unchecked: 'bg-gray-300',
      disabled: 'opacity-50 cursor-not-allowed',
      enabledUncheckedHover: 'hover:bg-gray-400',
      error: 'border-red-500', 
      thumbBase: 'pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out',
      thumbChecked: 'translate-x-5',
      thumbUnchecked: 'translate-x-0',
      labelBase: 'text-sm font-medium text-slate-700 select-none',
      labelDisabled: 'cursor-not-allowed opacity-70 text-gray-500',
      labelEnabled: 'cursor-pointer text-slate-700',
      labelSpacingLeft: 'mr-3',
      labelSpacingRight: 'ml-3',
      errorPaddingLeftLabel: 'pl-10 sm:pl-12',
    },
    checkbox: {
      visualBase: 'h-5 w-5 flex-shrink-0 inline-flex items-center justify-center border rounded mr-2 transition-all duration-150 ease-in-out',
      focus: 'ring-2 ring-sky-500 ring-offset-2 ring-offset-white',
      checked: 'bg-sky-600 border-sky-600',
      unchecked: 'bg-white border-gray-400',
      hoverChecked: 'hover:bg-sky-500 hover:border-sky-500',
      hoverUnchecked: 'hover:border-gray-500',
      disabled: 'opacity-60 cursor-not-allowed', 
      errorUnchecked: 'border-red-500', 
      labelBase: 'text-sm font-medium text-slate-700 select-none',
      labelDisabled: 'cursor-not-allowed opacity-70 text-gray-500',
      labelEnabled: 'cursor-pointer text-slate-700',
      checkIcon: 'w-4 h-4 text-white', 
      errorPaddingLeft: 'pl-7',
    },
    select: {
      buttonBase: 'w-full flex items-center justify-between px-3 py-2.5 bg-white border-gray-300 rounded-md text-slate-900 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition-shadow disabled:bg-gray-100 disabled:text-gray-500 disabled:cursor-not-allowed text-left',
      buttonError: 'border-red-500 text-red-700 focus:ring-red-500 focus:border-red-500',
      dropdownUl: 'absolute z-10 w-full mt-1 bg-white border-gray-300 rounded-md shadow-lg max-h-60 overflow-y-auto focus:outline-none',
      optionBase: 'px-3 py-2 text-sm flex items-center justify-between cursor-pointer',
      optionDisabled: 'text-gray-400 cursor-not-allowed bg-white',
      optionEnabled: 'text-slate-800 hover:bg-gray-100',
      optionFocusedEnabled: 'bg-gray-100 text-slate-900',
      noOptionsLi: 'px-3 py-2 text-gray-500 text-sm',
      expandIcon: 'w-5 h-5 text-gray-500 transform transition-transform duration-200',
      expandIconOpenState: 'rotate-180',
      placeholderText: 'text-gray-400', 
      optionLeadingIcon: 'w-5 h-5 mr-2 text-gray-500 flex-shrink-0',
      optionSelectedCheckIcon: 'w-5 h-5 text-sky-600 flex-shrink-0',
    },
    sidebarLayout: {
      container: 'flex',
      sidebar: 'flex-shrink-0 bg-gray-100 text-slate-900 border-r border-gray-200',
      main: 'flex-grow bg-white text-slate-900 overflow-y-auto',
    }
  }
};
